Cleanup to comply with zsh autoloader style

diff --git a/zsh/autoload/common/jstatd b/zsh/autoload/common/jstatd
--- a/zsh/autoload/common/jstatd
+++ b/zsh/autoload/common/jstatd
@@ -1,35 +1,37 @@
 #!/bin/zsh
 
-local exec='jstatd'
-local host="${host:-localhost}"
-local port="${port:-9090}"
+jstatd() {
+  local exec='jstatd'
+  local host="${host:-localhost}"
+  local port="${port:-9090}"
 
-if [[ -z "${JAVA_HOME}" ]]; then
-  echo "JAVA_HOME is not set"
-  return 1
-fi
+  if [[ -z "${JAVA_HOME}" ]]; then
+    echo "JAVA_HOME is not set"
+    return 1
+  fi
 
-if (( ! ${+commands[$exec]} )); then
-  echo "${exec} is not found in your system PATH"
-  return 1
-fi
+  if (( ! ${+commands[$exec]} )); then
+    echo "${exec} is not found in your system PATH"
+    return 1
+  fi
 
-local policy=${HOME}/.config/jstatd.all.policy
+  local policy=${HOME}/.config/jstatd.all.policy
 
-[[ -r ${policy} ]] || {
-  cat >"${policy}" <<'POLICY'
+  [[ -r ${policy} ]] || {
+    cat >"${policy}" <<'POLICY'
 grant codebase "file:${java.home}/lib/tools.jar" {
 permission java.security.AllPermission;
 };
 POLICY
-  chmod 600 "${policy}"
-}
+    chmod 600 "${policy}"
+  }
 
-"${exec}" \
-  -Djava.rmi.server.logCall=true \
-  -Djava.rmi.server.hostname="${host}" \
-  -Djava.security.policy="${policy}" \
-  -p "${port}" || {
-  echo "Failed to start ${exec}"
-  return 1
+  "${exec}" \
+    -Djava.rmi.server.logCall=true \
+    -Djava.rmi.server.hostname="${host}" \
+    -Djava.security.policy="${policy}" \
+    -p "${port}" || {
+    echo "Failed to start ${exec}"
+    return 1
+  }
 }
diff --git a/zsh/autoload/linux/os_release_json b/zsh/autoload/linux/os_release_json
--- a/zsh/autoload/linux/os_release_json
+++ b/zsh/autoload/linux/os_release_json
@@ -1,6 +1,7 @@
 #!/bin/zsh
 
-local code=$(cat <<'EOF'
+os_release_json() {
+  local code=$(cat <<'EOF'
 import json
 
 with open("/etc/os-release") as f:
@@ -14,19 +15,20 @@ print(json.dumps(d))
 EOF
 )
 
-local os_release_json=$(python3 -c "$code")
+  local os_release_json=$(python3 -c "$code")
 
-if [[ $? -ne 0 ]]; then
-  echo "Failed to get os-release"
-  return 1
-fi
-
-local os_release_data=$(echo "$os_release_json" | jq -r '.')
-
-if [[ $? -ne 0 ]]; then
-    echo "jq is not installed, install it to parse the json output"
-    echo "$os_release_json"
+  if [[ $? -ne 0 ]]; then
+    echo "Failed to get os-release"
     return 1
-fi
+  fi
 
-echo "$os_release_data"
+  local os_release_data=$(echo "$os_release_json" | jq -r '.')
+
+  if [[ $? -ne 0 ]]; then
+      echo "jq is not installed, install it to parse the json output"
+      echo "$os_release_json"
+      return 1
+  fi
+
+  echo "$os_release_data"
+}
diff --git a/zsh/autoload/linux/pulse_eq b/zsh/autoload/linux/pulse_eq
--- a/zsh/autoload/linux/pulse_eq
+++ b/zsh/autoload/linux/pulse_eq
@@ -1,25 +1,27 @@
 #!/bin/zsh
 
-if [[ -z "${1}" ]]; then
-  echo "Usage: ${0} [ device_name ]"
-  exit 1
-fi
+pulse_eq() {
+  if [[ -z "${1}" ]]; then
+    echo "Usage: ${0} [ device_name ]"
+    exit 1
+  fi
 
-local conf="${ZDOTDIR}/private/pulse-eq.conf"
+  local conf="${ZDOTDIR}/private/pulse-eq.conf"
 
-if [[ -f "${conf}" ]]; then
-  source "${conf}"
-else
-  echo "Could not source ${conf}"
-  exit 2
-fi
+  if [[ -f "${conf}" ]]; then
+    source "${conf}"
+  else
+    echo "Could not source ${conf}"
+    exit 2
+  fi
 
-local preset="${device_map[$1]}"
+  local preset="${device_map[$1]}"
 
-if [[ -z "${preset}" ]]; then
-  echo "Cannot find preset for device name '${1}'"
-  exit 3
-fi
+  if [[ -z "${preset}" ]]; then
+    echo "Cannot find preset for device name '${1}'"
+    exit 3
+  fi
 
-pulseeffects --load-preset "${preset}"
-gsettings set com.github.wwmm.pulseeffects last-used-output-preset "${preset}"
+  pulseeffects --load-preset "${preset}"
+  gsettings set com.github.wwmm.pulseeffects last-used-output-preset "${preset}"
+}
